language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_EMULATOR_LEVEL=22
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-$ANDROID_ABI-android-$ANDROID_EMULATOR_LEVEL

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_EMULATOR_LEVEL"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

before_script:
  - echo no | android create avd --force -n test -t android-$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck

after_script:
  - cat /home/travis/build/donfuxx/Mockinizer/mockinizer/build/reports/lint-results.xml
  - cat /home/travis/build/donfuxx/Mockinizer/mockinizer/build/reports/tests/testDebugUnitTest/index.html
  - cat /home/travis/build/donfuxx/Mockinizer/mockinizer/build/reports/androidTests/connected/index.html
